<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-9P5T93S" failures="0" tests="2" name="Default test" time="0.142" errors="0" timestamp="2021-03-24T19:22:50 CDT">
  <testcase classname="qaAcademy.DataProviderLoginTest" name="@BeforeTest initialization" time="0.02">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;String.contains(java.lang.CharSequence)&amp;quot; because &amp;quot;browserName&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "browserName" is null
at qaAcademy.base.initializeDriver(base.java:38)
at qaAcademy.DataProviderLoginTest.initialization(DataProviderLoginTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.beforeRun(TestRunner.java:607)
at org.testng.TestRunner.run(TestRunner.java:578)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest initialization -->
  <testcase classname="qaAcademy.DataProviderLoginTest" name="@AfterTest tearDown" time="-1.616631770887E9">
    <skipped/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="qaAcademy.DataProviderLoginTest" name="differentUserLogin" time="0.0">
    <skipped/>
  </testcase> <!-- differentUserLogin -->
  <testcase classname="qaAcademy.DataProviderLoginTest" name="differentUserLogin" time="0.0">
    <skipped/>
  </testcase> <!-- differentUserLogin -->
</testsuite> <!-- Default test -->
